- name: create directory for candy app
  file:
    path: /etc/docker/compose/candy
    state: directory
    mode: 0770
    owner: root
    group: docker

- name: deploy docker-compose.yml for candy app
  template:
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/candy/docker-compose.yml
    mode: 0640
    owner: root
    group: docker
  notify:
    - restart candy

- name: start & enable candy service
  service:
    name: docker-compose@candy
    # Сервис должен запускаться после перезагрузки
    enabled: yes
    # Сервис должен запуститься или быть уже запущен
    state: started

# Требуется для модуля docker_container
# https://docs.ansible.com/ansible/latest/modules/docker_container_module.html#requirements
- name: install python modules
  apt:
    name:
      - python3-docker
    update_cache: yes

# Требуется чтобы все обработчики (handlers) отработали немедленно,
# не дожидаясь обычных точек синхронизации
# https://docs.ansible.com/ansible/latest/modules/meta_module.html#parameters
- name: flush handlers
  meta: flush_handlers

- name: apply database migrations
  docker_container:
    name: db_migrator
    image: "{{ candy_image }}"
    command: ["candy-db", "upgrade", "head"]
    networks:
      - name: candy_default
    auto_remove: yes
    networks_cli_compatible: yes
    env:
      CANDY_DB_URL: postgresql://{{ candy_pg_user }}:{{ candy_pg_password }}@postgres/{{ candy_pg_dbname }}
